{% set name = "delfies" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/delfies-{{ version }}.tar.gz
  sha256: 92fc8c57d98a41aac1bbb265a144d816479593dbdd33d445038e26489b2910c0

build:
  entry_points:
    - delfies = delfies.delfies:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - pysam >=0.22.0,<0.23.0
    - pybedtools >=0.9.1,<0.10.0
    - click >=8.1.7,<9.0.0
    - rich-click >=1.7.3,<2.0.0
    - pyfastx >=2.1.0,<3.0.0
    - datasci-bricoletc >=0.1.1,<0.2.0
    - edlib >=1.3.9,<2.0.0

test:
  imports:
    - delfies
  commands:
    - pip check
    - delfies --help
  requires:
    - pip

about:
  summary: delfies is a tool for the detection of DNA Elimination breakpoints
  home: https://github.com/bricoletc/delfies
  license: MIT
  license_file: LICENSE

extra:
  dev_url: https://github.com/bricoletc/delfies
  identifiers:
    - doi:10.21105/joss.07385
  recipe-maintainers:
    - kbseah
